name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ImageCropper
            asset_name: ImageCropper-macos-x86_64
            use_bundle: true
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ImageCropper
            asset_name: ImageCropper-macos-aarch64
            use_bundle: true
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ImageCropper
            asset_name: ImageCropper-linux-x86_64
            use_bundle: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ImageCropper.exe
            asset_name: ImageCropper-windows-x86_64
            use_bundle: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cargo-bundle
        if: matrix.use_bundle == true
        run: cargo install cargo-bundle

      - name: Build (Binary)
        if: matrix.use_bundle == false
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build (Bundle)
        if: matrix.use_bundle == true
        run: cargo bundle --release --target ${{ matrix.target }}

      - name: Zip Artifact (MacOS)
        if: matrix.use_bundle == true
        run: |
          cd target/${{ matrix.target }}/release/bundle/osx/
          zip -r ../../../../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}.app

      - name: Zip Artifact (Linux)
        if: runner.os == 'Linux'
        run: |
          cd target/${{ matrix.target }}/release/
          zip ../../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}

      - name: Zip Artifact (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release/
          7z a ../../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}.zip
